

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "68", "71", "72"],
		"CDFG" : "viterbi_decoder",
		"Protocol" : "ap_ctrl_none",
		"ControlExist" : "0", "ap_start" : "0", "ap_ready" : "0", "ap_done" : "0", "ap_continue" : "0", "ap_idle" : "0", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "51", "EstimateLatencyMax" : "51",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "encoded_in", "Type" : "Axis", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "encoded_in_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "decoded_out", "Type" : "Axis", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "decoded_out_TDATA_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_4_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_5_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_6_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_7_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_8_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_9_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_10_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_11_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_12_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_13_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_14_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_15_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_16_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_17_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_18_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_19_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_20_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_21_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_22_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_23_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_24_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_25_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_26_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_27_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_28_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_29_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_30_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_31_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_32_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_33_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_34_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_35_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_36_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_37_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_38_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_39_U", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_40_U", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_41_U", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_42_U", "Parent" : "0"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_43_U", "Parent" : "0"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_44_U", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_45_U", "Parent" : "0"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_46_U", "Parent" : "0"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_47_U", "Parent" : "0"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_48_U", "Parent" : "0"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_49_U", "Parent" : "0"},
	{"ID" : "51", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_50_U", "Parent" : "0"},
	{"ID" : "52", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_51_U", "Parent" : "0"},
	{"ID" : "53", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_52_U", "Parent" : "0"},
	{"ID" : "54", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_53_U", "Parent" : "0"},
	{"ID" : "55", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_54_U", "Parent" : "0"},
	{"ID" : "56", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_55_U", "Parent" : "0"},
	{"ID" : "57", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_56_U", "Parent" : "0"},
	{"ID" : "58", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_57_U", "Parent" : "0"},
	{"ID" : "59", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_58_U", "Parent" : "0"},
	{"ID" : "60", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_59_U", "Parent" : "0"},
	{"ID" : "61", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_60_U", "Parent" : "0"},
	{"ID" : "62", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_61_U", "Parent" : "0"},
	{"ID" : "63", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_62_U", "Parent" : "0"},
	{"ID" : "64", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.survivor_63_U", "Parent" : "0"},
	{"ID" : "65", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRELLIS_fu_813", "Parent" : "0", "Child" : ["66", "67"],
		"CDFG" : "viterbi_decoder_Pipeline_TRELLIS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "survivor_63", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_62", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_61", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_60", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_59", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_58", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_57", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_56", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_55", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_54", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_53", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_52", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_51", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_50", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_49", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_48", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_47", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_46", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_45", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_44", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_43", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_42", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_41", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_40", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_39", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_38", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_37", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_36", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_35", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_34", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_33", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_32", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "survivor", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "rx_sym", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_2", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_3", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_4", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_5", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_6", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_7", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_8", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_9", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_15", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_10", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_11", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_12", "Type" : "None", "Direction" : "I"},
			{"Name" : "rx_sym_13", "Type" : "None", "Direction" : "I"},
			{"Name" : "empty", "Type" : "None", "Direction" : "I"},
			{"Name" : "p_0_0_0843_63139_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_62137_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_61135_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_60133_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_59131_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_58129_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_57127_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_56125_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_55123_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_54121_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_53119_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_52117_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_51115_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_50113_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_49111_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_48109_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_47107_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_46105_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_45103_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_44101_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_4399_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_4297_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_4195_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_4093_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3991_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3889_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3787_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3685_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3583_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3481_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3379_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3277_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3175_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_3073_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2971_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2869_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2767_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2665_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2563_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2461_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2359_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2257_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2155_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_2053_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1951_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1849_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1747_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1645_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1543_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1441_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1339_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1237_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1135_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_1033_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_931_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_829_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_727_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_625_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_523_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_421_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_319_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_217_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_0_0843_115_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_0_086513_out", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "TRELLIS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRELLIS_fu_813.sparsemux_33_4_2_1_1_U1", "Parent" : "65"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRELLIS_fu_813.flow_control_loop_pipe_sequential_init_U", "Parent" : "65"},
	{"ID" : "68", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRACEBACK_fu_1025", "Parent" : "0", "Child" : ["69", "70"],
		"CDFG" : "viterbi_decoder_Pipeline_TRACEBACK",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "18", "EstimateLatencyMax" : "18",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "best_state_32", "Type" : "None", "Direction" : "I"},
			{"Name" : "survivor", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_31", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_32", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_33", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_34", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_35", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_36", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_37", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_38", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_39", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_40", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_41", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_42", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_43", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_44", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_45", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_46", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_47", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_48", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_49", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_50", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_51", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_52", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_53", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_54", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_55", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_56", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_57", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_58", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_59", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_60", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_61", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_62", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "survivor_63", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "p_out", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out1", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out2", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out3", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out5", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out6", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out7", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out8", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out9", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out10", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out11", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out12", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out13", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out14", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "p_out15", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "TRACEBACK", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRACEBACK_fu_1025.sparsemux_129_6_1_1_1_U147", "Parent" : "68"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_viterbi_decoder_Pipeline_TRACEBACK_fu_1025.flow_control_loop_pipe_sequential_init_U", "Parent" : "68"},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_encoded_in_U", "Parent" : "0"},
	{"ID" : "72", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_decoded_out_U", "Parent" : "0"}]}
